name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    env:
      MIX_ENV: test
    strategy:
      matrix:
        include:
          - elixir: "1.14.5"
            otp: "26.0"
            testArgs: "--exclude=lts_only"
          - elixir: "1.15.4"
            otp: "26.0"
            testArgs: "--exclude=lts_only"
          - elixir: "1.16.0"
            otp: "26.0"
            testArgs: "--exclude=lts_only"
          - elixir: "1.17.3"
            otp: "27.0"
            testArgs: "--exclude=lts_only"
          - elixir: "1.18.0"
            otp: "27.0"
            testArgs: "--exclude=lts_only"
          - elixir: "1.18.4"
            otp: "27.0"
            testArgs: "--exclude=lts_only"
          - elixir: "1.19.0"
            otp: "28.1"
            testArgs: ""
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: mix deps.get
      - name: Check compile warnings
        run: mix compile --warnings-as-errors
      - name: Check format
        run: mix format --check-formatted
      # TODO add dialyzer?
      - name: Unit tests
        run: mix test ${{ matrix.testArgs }}
