name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        include:
          - elixir: 1.12.1
            otp: 24.0.2
          - elixir: 1.13.0
            otp: 24.0.2
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: mix deps.get
      - name: Check compile warnings
        run: mix compile --warnings-as-errors
      # TODO add dialyzer?
      - name: Unit tests
        run: mix test

  format:
    runs-on: ubuntu-latest
    name: Format (Elixir ${{matrix.elixir}})
    strategy:
      matrix:
        include:
          - elixir: 1.13.0
            otp: 24.0.2
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: mix deps.get
      - name: Check format
        run: mix format --check-formatted
